export const projects = [
  {
    id: 1,
    title: "NEBULA — WebGL Commerce",
    category: "WebGL / E-commerce",
    filter: "webgl",
    description: "Immersive 3D sneaker configurator with real-time lighting, physics-based materials and 60fps checkout. +212% conversion.",
    image: "https://images.pexels.com/photos/29450016/pexels-photo-29450016.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["Three.js", "React", "GSAP", "Shopify"],
    year: "2025",
    stats: "212% CR",
    color: "#d4ff3f",
    link: "#",
  },
  {
    id: 2,
    title: "PULSE — AI Analytics OS",
    category: "AI / SaaS Dashboard",
    filter: "ai",
    description: "Living data organism. Streaming LLM insights visualized as a particle galaxy with voice control and predictive UI.",
    image: "https://images.pexels.com/photos/27141316/pexels-photo-27141316.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["Next.js", "Python", "Framer", "OpenAI"],
    year: "2025",
    stats: "40k users",
    color: "#22d3ee",
    link: "#",
  },
  {
    id: 3,
    title: "MIRAGE — Virtual Gallery",
    category: "Metaverse / Art",
    filter: "webgl",
    description: "Browser-based metaverse gallery for 120+ digital artists. Spatial audio, avatars and NFT minting in one click.",
    image: "https://images.pexels.com/photos/28494632/pexels-photo-28494632.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["WebXR", "Three.js", "Solidity", "Blender"],
    year: "2024",
    stats: "1.2M visits",
    color: "#8b5cf6",
    link: "#",
  },
  {
    id: 4,
    title: "ORBITAL — Fintech Landing",
    category: "Brand / Motion",
    filter: "brand",
    description: "Award-winning scroll odyssey for a space fintech. Shaders, Lenis smooth scroll and magnetic everything.",
    image: "https://images.pexels.com/photos/29506609/pexels-photo-29506609.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["React", "Shaders", "Lenis", "Sanity"],
    year: "2024",
    stats: "Awwwards SOTD",
    color: "#fb7185",
    link: "#",
  },
  {
    id: 5,
    title: "SYNTH — Music DAW in Browser",
    category: "Web Audio / AI",
    filter: "ai",
    description: "Collaborative browser DAW with AI stem separation, 3D mixer and latency-free jamming via WebRTC.",
    image: "https://images.pexels.com/photos/27141307/pexels-photo-27141307.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["Tone.js", "WebGPU", "CRDT", "Tailwind"],
    year: "2023",
    stats: "120k tracks",
    color: "#facc15",
    link: "#",
  },
  {
    id: 6,
    title: "TERRA — Climate Data Story",
    category: "Data Viz / Brand",
    filter: "brand",
    description: "Interactive climate atlas turning 40 years of NASA data into an emotional scroll-driven documentary.",
    image: "https://images.pexels.com/photos/29355999/pexels-photo-29355999.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    tags: ["D3.js", "R3F", "Storytelling"],
    year: "2023",
    stats: "FWA Winner",
    color: "#34d399",
    link: "#",
  },
];

export const skills = [
  { name: "React / Next.js", level: 98, icon: "atom" },
  { name: "Three.js / WebGL", level: 94, icon: "box" },
  { name: "TypeScript", level: 92, icon: "code" },
  { name: "GSAP / Motion", level: 96, icon: "sparkles" },
  { name: "Node / Edge", level: 88, icon: "server" },
  { name: "Blender / Shaders", level: 85, icon: "shapes" },
];

export const experience = [
  {
    role: "Lead Creative Developer",
    company: "SUPERNOVA Studio",
    period: "2023 — Now",
    location: "Tokyo / Remote",
    desc: "Leading a squad of 8 crafting WebGL flagships for Nike, Spotify & Aesop. Shipped 14 Awwwards-level launches.",
    tags: ["Leadership", "WebGL", "R&D"],
  },
  {
    role: "Senior Frontend Engineer",
    company: "Lumen AI",
    period: "2021 — 2023",
    location: "San Francisco",
    desc: "Built real-time AI dashboard used by 40k teams. Cut bundle 62%, pioneered RSC + partial 3D hydration.",
    tags: ["Next.js", "AI UX", "Performance"],
  },
  {
    role: "Interactive Developer",
    company: "Studio Freight Clone",
    period: "2019 — 2021",
    location: "Berlin",
    desc: "Scroll experiences, shaders and e-commerce theatrics. 3x FWA, 1x Cannes shortlist.",
    tags: ["Shaders", "E-com", "Motion"],
  },
  {
    role: "Freelance Web Designer",
    company: "Self-employed",
    period: "2017 — 2019",
    location: "Worldwide",
    desc: "120+ projects for startups. Learned to sell, ship and survive. Obsessed with detail ever since.",
    tags: ["Branding", "Clients", "Hustle"],
  },
];

export const testimonials = [
  {
    quote: "Kai doesn't build websites. He builds gravity wells — users fall in and don't want to leave. Our conversion tripled.",
    name: "Maya Chen",
    role: "CPO, Nebula Footwear",
    avatar: "MC",
  },
  {
    quote: "The single most detail-obsessed developer I've worked with. Every frame feels intentional. Every interaction sings.",
    name: "Jonas Weber",
    role: "Founder, Lumen AI",
    avatar: "JW",
  },
  {
    quote: "He turned 40 years of boring climate data into a story that made our board cry. In a good way.",
    name: "Dr. Amara Okafor",
    role: "Director, Terra Project",
    avatar: "AO",
  },
];
